### ISSUE TITLE
Tests aren't working, README pretty limited

### ISSUE THREAD

**Issue by rfay** [fwust/ddev-env-file#1]
I note that the tests are failing on this add-on, and the README is pretty general. 

If this is intended for general consumption, could you improve those?

If it's not intended for general use, could you remove the `ddev-get` topic so that it doesn't show up in `ddev get --list --all` ?

Thanks!
-Randy

**Comment by fwust** [comment]
Sure, i'm sorry. I've removed the `ddev-get` topic

**Comment by rfay** [comment]
If you find it useful to other people, update the README and add the label back. Thanks!

**Comment by rfay** [comment]
You can still use it with `ddev get fwust/ddev-env-file` just fine. The label is not related there.
